stacktrace: fix a C23-ism in sigint_handler
clang 21 doesn't like ommitting a parameter name when not in C23 mode.

stacktrace.c:1138:44: error: omitting the parameter name in a function definition is a C23 extension [-Werror,-Wc23-extensions]
 1138 | static void sigint_handler (int /* signo */)
      |                                            ^
1 error generated.

	* src/stacktrace.c (sigint_handler): Use attribute unused.

Signed-off-by: Mark Wielaard <mark@klomp.org>